### PR TITLE
Make upgrade and update minimum Go version to 1.21

### PR DESCRIPTION
**Pull request by bufdev**
This is practically ready for merge once 1.23 is released. Do a `make upgrade` before merging.

### CODE REVIEW

**Comment by bufdev** [comment]
FYI @doriable @oliversun9 @pkwarren I'm keeping this branch up to date in anticipation of 1.23 release, ignoring other dependabots for now

**Comment by bufdev** [comment]
Likely relies on https://github.com/golangci/golangci-lint/pull/4836 being merged. Also https://hub.docker.com/_/golang needs `1.23`.

**Comment by bufdev** [comment]
Docker updated in https://github.com/docker-library/golang/pull/529, just waiting on `golangci-lint`.

**Comment by bufdev** [comment]
Actually now need https://github.com/docker-library/official-images/pull/17359.

**Review by smallsamantha — APPROVED** [review]

**Comment by bufdev** [comment]
Temporarily downgrading the Docker images to 1.22 until the 1.23 images are available - this actually has no effect since `go.mod` has `toolchain` set to `1.23.0`, which is what will be used for builds.

**Pull request merged**
