### PR TITLE
Rename pkg/manifest to bufpkg/bufmanifest

### PR DESCRIPTION
**Pull request by bufdev**
First half of https://linear.app/bufbuild/issue/TCN-1064/pkgmanifest-should-be-moved-to-bufpkgbufmanifest. A change to core will be required after, which I will hand off.

### CODE REVIEW

**Review by pkwarren — APPROVED** [review]

**Comment by twilly** [comment]
Can we instead move the protobuf types out of the package? That's the only dependency and the mapping funcs were there for convenience. We should have put those in a different package.

**Review by twilly — CHANGES_REQUESTED** [review]
I don't think this is the right thing to do yet. Let me think some more before landing.

**Comment by twilly** [comment]
PR #1762 is an alternative to wholesale moving the package. IMHO it's clearer but I'd like to know what others think.

**Comment by bufdev** [comment]
Closing in favor of #1762

**Pull request closed without merging**
