### PR TITLE
Promote beta registry organization, module, label and commit commands

### LINKED ISSUE #1431: Promote `buf beta registry <organization, module, label, commit>` to stable
This includes merging all of the `buf beta registry` commands with `buf registry` commands

### PR DESCRIPTION
**Pull request by oliversun9**
This PR moves `[module, organization, label, commit]` commands out of beta. Here are pruned outputs of `--help-tree` before and after.

Before

```
buf registry  --help-tree
registry         Manage assets on the Buf Schema Registry
  archive        Archive one or more labels for the given input
  commit         Manage a repository's commits
    get          Get commit details
    list         List repository commits
  label          Manage a repository's labels
    create       Create a label for a specified commit
    get          Get label details
    list         List repository labels
  organization   Manage organizations
    create       Create a new BSR organization
    delete       Delete a BSR organization
    get          Get a BSR organization
  repository     Manage repositories
    create       Create a BSR repository
    delete       Delete a BSR repository
    deprecate    Deprecate a BSR repository
    get          Get a BSR repository
    list         List BSR repositories
    undeprecate  Undeprecate a BSR repository
    update       Update BSR repository settings
  unarchive      Unarchive one or more labels for the given input
```

After

```
buf registry  --help-tree            
registry         Manage assets on the Buf Schema Registry
  commit         Manage a module's commits
    add-label    Add labels to a commit
    info         Get commit information
    list         List modules commits
    resolve      Resolve commit from a reference
  label          Manage a module's labels
    archive      Archive a module label
    info         Show label information
    list         List module labels
    unarchive    Unarchive a module label
  module         Manage BSR modules
    create       Create a BSR module
    delete       Delete a BSR module
    deprecate    Deprecate a BSR module
    info         Get a BSR module
    undeprecate  Undeprecate a BSR module
    update       Update BSR module settings
  organization   Manage organizations
    create       Create a new BSR organization
    delete       Delete a BSR organization
    info         Show information about a BSR organization
    update       Update a BSR organization
```

Fixes #1431

### CODE REVIEW

**Comment by doriable** [comment]
A couple of UX questions I have (mostly for @bufdev) from QA-ing the commands:
- `buf registry module info` -- should we include the `ModuleState` (e.g. deprecated vs. active) in the `json` output?
- `buf registry commit list`/`buf registry commit info` -- should we include the review state (e.g. pending, approved, rejected) in the `json` output?

**Comment by bufdev** [comment]
> buf registry module info -- should we include the ModuleState (e.g. deprecated vs. active) in the json output?

Yes

> buf registry commit list/buf registry commit info -- should we include the review state (e.g. pending, approved, rejected) in the json output?

No

**Comment by bufdev** [comment]
Overall looks good, @doriable and @oliversun9 I want to rely on the two of you to check off that this faithfully implements the spec. If it does, let's just get it in, I don't want to go line-by-line on this one (and don't think I have to).

**Comment by oliversun9** [comment]
> > buf registry module info -- should we include the ModuleState (e.g. deprecated vs. active) in the json output?
> 
> Yes
> 
> > buf registry commit list/buf registry commit info -- should we include the review state (e.g. pending, approved, rejected) in the json output?
> 
> No

`buf registry module info` now includes module state in its json output.

```
$ buf registry module info buf.build/googleapis/googleapis --format json | jq
{
  "id": "c84e502e8a354bdcaae4a5dbdf9a685c",
  "remote": "buf.build",
  "owner": "googleapis",
  "name": "googleapis",
  "create_time": "2022-09-06T17:15:20.275814Z",
  "state": "MODULE_STATE_ACTIVE"
}

$ buf registry module info buf.build/beta/wellknowntypes --format json | jq
{
  "id": "e64bf10a11df4b088391ab4c466937e9",
  "remote": "buf.build",
  "owner": "beta",
  "name": "wellknowntypes",
  "create_time": "2021-07-23T12:58:12.435945Z",
  "state": "MODULE_STATE_DEPRECATED"
}
```

**Comment by doriable** [comment]
> Overall looks good, @doriable and @oliversun9 I want to rely on the two of you to check off that this faithfully implements the spec. If it does, let's just get it in, I don't want to go line-by-line on this one (and don't think I have to).

Yep, can do! I went through each command and tested against the spec, can do this again given the new updates.

**Comment by oliversun9** [comment]
> > Overall looks good, @doriable and @oliversun9 I want to rely on the two of you to check off that this faithfully implements the spec. If it does, let's just get it in, I don't want to go line-by-line on this one (and don't think I have to).
> 
> Yep, can do! I went through each command and tested against the spec, can do this again given the new updates.

Me too!

**Comment by oliversun9** [comment]
I have tested it against the spec

**Review by doriable — APPROVED** [review]

**Pull request merged**
