### PR TITLE
Implement new formatting for use arg statements

### PR DESCRIPTION
**Pull request by lucperkins**
This PR proposes a new way of path formatting inputs in `Use` statements. The issue with the current system is that it's unclear which parts of the path are variables and which aren't. Here's an example:

```
Usage:
  buf beta registry plugin create <buf.build/owner/plugins/plugin> [flags]
```

It's not clear here that `owner` and `plugin` are variables whereas `plugins` is not and `buf.build` is optional. My proposed format:

```
(buf.build)/{owner}/plugins/{plugin}
```

With this information, I know that I need to run e.g.:

```shell
buf beta registry plugin create my-registry.io/lucperkins/plugins/my-plugin --visibility public
```

I'm fully open to suggestion on this but I do think that we need a way to communicate this to users more clearly.

### CODE REVIEW

**Comment by lrewega** [comment]
It's perhaps worth noting that `buf.build` is a variable as well, in the case where you are using a private registry.

**Comment by lucperkins** [comment]
@lrewega Ah yes, a fair concern. I wonder if there's any prior art here that we could adopt. Perhaps we could have different syntax for default tags? Something like `(buf.build)/{user}/plugins/{plugin}` might be an option for that.

**Comment by bufdev** [comment]
Do we want to merge this? This might need updating re: https://github.com/bufbuild/buf/pull/909

**Comment by lucperkins** [comment]
@bufdev I think I'd prefer to hold off. I want to figure out a way to synchronize this across docs and such but I haven't quite found the right approach just yet.

**Pull request closed without merging**
