### PR TITLE
A read bucket for git trees

### PR DESCRIPTION
**Pull request by twilly**
Modules are built from buckets, meaning if we want to build a module from git, then we'll need a bucket for it. It's possible to checkout a git commit and build from a storageos bucket but there's a better way: read directly from git's storage.

go-git exposes an API for reading git objects, including git trees. Trees are how git represents and stores files. Gluing a storage bucket onto go-git's tree API means we can build a module out of a git repository without copying file content to a filesystem.

Here's a rough example of how to instantiate a bucket from a git repository's HEAD commit:

```go
import (
  "github.com/bufbuild/buf/private/pkg/git"
  gogit "github.com/go-git/go-git/v5"
)

var repo *gogit.Repository

head, _ := repo.Head()
commit, _ := repo.CommitObject(head.Hash())
tree, _ := commit.Tree()
bucket := NewTreeReader(tree)
```

### CODE REVIEW

**Review by bufdev — CHANGES_REQUESTED** [review]
https://github.com/bufbuild/buf/issues/34

go-git was a disaster for us, I had to spend a lot of time and energy ripping it out early on - I am hard against depending on it in any way unless something major has changed.

**Comment by bufdev** [comment]
Also note that go-git secretly doesn't use pure Golang in certain cases: https://github.com/go-git/go-git/commit/a0ff9a899d66243dfcfc30993ed9bf3d6c982400

**Comment by bufdev** [comment]
For some context, @twilly and I caught up offline, we're going to find a fun solution cuz git-based buckets would be great

**Comment by twilly** [comment]
Closing this in favor of a go-git-less edition, currently drafted as PR #2018.

**Pull request closed without merging**
