### PR TITLE
Delete twirp

### PR DESCRIPTION
**Pull request by bufdev**

### CODE REVIEW

**Review by doriable — APPROVED** [review]

**Review by johanbrandhorst — APPROVED** [review]
:salute_canada:

**Comment by mculp** [comment]
I just found this repo, was looking through it, and was just wondering why twirp was deleted? I don't see any context in the PR or commit msg

**Comment by cep21** [comment]
Also curious.  Is buf not a good fit for people using twirp?

**Comment by bufdev** [comment]
This was an implementation detail - for a while, we had code that supported the BSR's API (that `buf` talks to) both over Twirp and gRPC. We never actually exposed Twirp publicly via our API. This PR just deleted that unused code.

Buf is a fine fit for people using Twirp, including `protoc-gen-twirp` - this PR is completely unrelated to `buf`s usability with any plugin. Buf is meant to be used with all Protobuf plugins.

**Pull request merged**
