### PR TITLE
Upgrade protoreflect version

### PR DESCRIPTION
**Pull request by johanbrandhorst**
Pending https://github.com/jhump/protoreflect/pull/477

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
I still have not received feedback from the affected customer as to whether this fixed their issue.

**Comment by bufdev** [comment]
I would merge regardless and not block on the customer getting back

**Comment by johanbrandhorst** [comment]
Since this isn't yet merged into `protoreflect`'s master branch, we should update to the new master commit as soon as https://github.com/jhump/protoreflect/pull/477 is merged.

**Comment by bufdev** [comment]
Oh I did not realize this isn't merged into protoreflect - we should definitely wait on that, we only want to depend on protoreflect master

**Comment by johanbrandhorst** [comment]
Ha, ok, I'll do a quick revert and we can reopen this.

**Comment by johanbrandhorst** [comment]
https://github.com/bufbuild/buf/pull/844

**Comment by johanbrandhorst** [comment]
I won't reopen this - I'm subscribed to the protoreflect PR and will create a new one once that has been merged. I've left the branch intact so that it's still possible for the customer to build from this branch to test their panic.

**Pull request merged**
