### PR TITLE
add namespace to audit log actions

### PR DESCRIPTION
**Pull request by smallsamantha**

### CODE REVIEW

**Review by johanbrandhorst — APPROVED** [review]
LGTM, but hold off until #783 is merged of course.

**Comment by cyinma** [comment]
> LGTM, but hold off until #783 is merged of course.

how about removing those in DisplayService and merge this first, and I follow this practice in my PR?
as the RPC names are still refining in DisplayService

**Comment by smallsamantha** [comment]
> > LGTM, but hold off until #783 is merged of course.
> 
> how about removing those in DisplayService and merge this first, and I follow this practice in my PR? as the RPC names are still refining in DisplayService

sure, that works! will update now

**Review by johanbrandhorst — APPROVED** [review]
LGTM

**Pull request merged**
