### PR TITLE
Update storageos package to support following symlinks on Windows

### PR DESCRIPTION
**Pull request by tehbilly**
This should address #1443

### CODE REVIEW

**Comment by bufdev** [comment]
It was intentional - I don't remember exactly the reasoning, but from our research, symlinks in Windows were (1) not normal (2) required elevated permissions, if I remember correctly. We didn't want to support what we didn't understand, and unless we have more research on the topic, we should stick to that.

**Review by bufdev — CHANGES_REQUESTED** [review]
Blocking unless we have more data on symlinks in Windows

**Comment by bufdev** [comment]
@doriable might have some recollection of this as well

**Comment by tehbilly** [comment]
The creation of symlinks prior to Windows 10 required admin privileges, but [as of 2016](https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/) it can be done with either admin privs or by using [developer mode](https://learn.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development). However, there shouldn't be any permissions for reading/following the links unless they're explicitly added _(just like normal files)_.

The included tests, the ones I removed the `t.Skip` call from, do actually catch this case. If you check out the repo with git's `core.symlinks` set to `false` the tests will fail, but with it set to `true` the tests pass the same as on MacOS/Linux.

**Comment by bufdev** [comment]
I'd want a few more pieces of input about this as I remember this being a universal/uncontroversial decision - do we have others who remember the context here with Windows? This is a one-way-door that we can't take back, so I don't want to make this decision lightly.

**Comment by tehbilly** [comment]
Absolutely agree! If there were specific concerns it'd be nice to have a chance to address them. If not, perhaps we could add a warning when they're encountered on Windows, letting users know that they're skipped intentionally and they're not encountering a bug.

**Comment by doriable** [comment]
I think the original decision was very much based on the fact that outside of Windows 10, symlinks are bespoke on NTFS. That being said, given that it does work on Windows 10, I can see the argument for enabling this. I think there should be an understanding that this will absolutely break on older systems and we will not be supporting that, but otherwise this seems like a reasonable course of action?

**Review by doriable — APPROVED** [review]

**Review by bufdev — APPROVED** [review]
We're just going to go ahead with this, having done more research

**Pull request merged**
